### ISSUE TITLE
Use a folder in the SD

### ISSUE THREAD

**Issue by CesarHerreraG** [TronFortyTwo/sturmreader#14]
What exactly have I to do to use the books in SD and not copying them in other place too?

**Comment by TronFortyTwo** [comment]
If you use the Plus version you can select a custom path for your book folder

**Comment by CesarHerreraG** [comment]
But they have been copied inside the app.
I don't know how to do it exactly.

**Comment by TronFortyTwo** [comment]
Sorry, but I don't understand exactly what you mean

**Comment by CesarHerreraG** [comment]
I have a folder in Documents/Libros in the SD card and I want Sturm access them without duplicate them inside Sturm.

**Comment by TronFortyTwo** [comment]
Ok thanks, I understand

**Comment by TronFortyTwo** [comment]
I see this may be a problem for some users, especially with big book libraries and with devices with limited storage, but by design confined Ubuntu Touch apps can't access external folders, and I don't plan to make Sturm Reader an unconfined app for now.
If you think (as it may be) a major system limitation you can file a report on Ubuntu Touch itself about this using this problem as example. If other apps and users find this limitation critical enought Ubuntu Touch itself may provide some system to access external folder that Sturm will use to fix this issue without breaking confinement.

**Comment by CesarHerreraG** [comment]
Thanks
