### ISSUE TITLE
bottom control bar partly unusable in portrait mode

### ISSUE THREAD

**Issue by Danfro** [TronFortyTwo/sturmreader#32]
Xperia X, devel

When opening a pdf in portrait mode, the home button in the bottom controls bar is obstructed by other buttons and therefore not usable.
Maybe button size (or margins) can be reduced a bit in portrait mode to fit all buttons on the screen?

For some reason the buttons come up fine on my E5.

Does the app maybe use the systems scaling setting for sizing the buttons? That is different for devices.

![screenshot20200928_130413529](https://user-images.githubusercontent.com/37637312/94453508-09c9ee80-01b1-11eb-8e1f-5a0d5f3bacd3.png)

**Comment by TronFortyTwo** [comment]
Thanks for the report! When you say it happens when you open a pdf file, this means that when opening epubs it is scaled correctly or you just haven't tested that?

**Comment by Danfro** [comment]
I havn't tested that yet. I need to get an ebook first. ;-)

**Comment by Danfro** [comment]
Just tested an ebook on my Xperia. Same broken button layout.

--

**Comment by TronFortyTwo** [comment]
This is strange since the code should automatically resize buttons when they don't fit a smaller screen. When I test that on my devices (E5, M10) it just works. I tried something with the code and some clean-up. Could you please test the new click I am sending here (since github doesn't allow to upload .click I zipped it) Thank you :D
If this doesn't work neither it's a very weird issue


[sturmreader.emanuelesorce_3.1.0_arm64.click.zip](https://github.com/TronFortyTwo/sturmreader/files/5298502/sturmreader.emanuelesorce_3.1.0_arm64.click.zip)

And if you could also attach a log could be helpful in case there's some error somewhere

**Comment by Danfro** [comment]
Thanks a lot for digging into this. Could you please share a armhf click? I was not brave enough to swap to 64bit yet. ;-)

**Comment by TronFortyTwo** [comment]
Here it comes :)
[sturmreader.emanuelesorce_3.1.0_armhf.click.zip](https://github.com/TronFortyTwo/sturmreader/files/5300372/sturmreader.emanuelesorce_3.1.0_armhf.click.zip)

**Comment by Danfro** [comment]
It's magic! 😉



--

**Comment by Danfro** [comment]
Ok, so sending a screenshot as email attachment obviously does not work ^^.

Whatever you did, it solved the issue. All buttons looking fine on both of my devices now. Great! Thanks a lot.

![screenshot20200929_192442029](https://user-images.githubusercontent.com/37637312/94601102-466e1680-0293-11eb-8933-b841db04fb07.png)

Closing this now. Let's call it solved.

**Comment by TronFortyTwo** [comment]
Great! Not sure what I did either, but the code that scaled the buttons was kinda messy... I just sorted it up! When they say good code style pay off :D
